---
version: "3"
services:
 devopsdb:
   image: chasya07/repo:dbimg
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb
   ports:
     - "3306:3306"

 application:
   image: chasya07/repo:appimg
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
